# Generated by Django 5.0.6 on 2026-06-11 14:53

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def hash_existing_otps(apps, schema_editor):
    EmailOTP = apps.get_model('accounts', 'EmailOTP')
    for otp_record in EmailOTP.objects.all():
        if hasattr(otp_record, 'otp') and otp_record.otp:  # Just in case
            otp_record.otp_hash = make_password(otp_record.otp)
            otp_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_reliability_indexes'),
    ]

    operations = [
        # Step 1: Add the new otp_hash field, allow null temporarily
        migrations.AddField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        # Step 2: Hash existing OTPs
        migrations.RunPython(hash_existing_otps, migrations.RunPython.noop),
        # Step 3: Remove the old otp field
        migrations.RemoveField(
            model_name='emailotp',
            name='otp',
        ),
    ]
