# Generated by Django 5.0.6 on 2026-09-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0011_answer_unique_answer_per_attempt_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('attempt_started', 'Attempt started'), ('question_viewed', 'Question viewed'), ('answer_saved', 'Answer saved'), ('answer_changed', 'Answer changed'), ('question_skipped', 'Question skipped'), ('exam_submitted', 'Exam submitted'), ('exam_terminated', 'Exam terminated')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='exams.examattempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_events', to='exams.question')),
            ],
            options={
                'indexes': [models.Index(fields=['attempt', 'timestamp'], name='attempt_event_attempt_time_idx'), models.Index(fields=['event_type', 'timestamp'], name='attempt_event_type_time_idx')],
            },
        ),
    ]
