# Generated by Django 5.0.6 on 2026-09-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptevent',
            name='event_type',
            field=models.CharField(choices=[('attempt_started', 'Attempt started'), ('question_viewed', 'Question viewed'), ('answer_saved', 'Answer saved'), ('answer_changed', 'Answer changed'), ('question_skipped', 'Question skipped'), ('question_navigation', 'Question navigation'), ('app_backgrounded', 'App backgrounded'), ('app_resumed', 'App resumed'), ('network_offline', 'Network offline'), ('network_restored', 'Network restored'), ('exam_submitted', 'Exam submitted'), ('exam_terminated', 'Exam terminated')], max_length=32),
        ),
    ]
