# Generated by Django 5.0.6 on 2026-06-11 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_examattempt_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'exam'), name='unique_active_attempt_per_user_exam'),
        ),
    ]
