# Generated by Django 5.0.6 on 2026-09-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_reliability_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
