# Generated by Django 5.0.6 on 2026-09-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_screenshot_screenshot_timestamp_desc_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
