# Generated by Django 5.0.6 on 2026-06-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_seed_sample_coupons'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organisationinvite',
            index=models.Index(fields=['email', 'accepted'], name='orginvite_email_accepted_idx'),
        ),
    ]
