# Generated by Django 5.0.6 on 2026-06-12 03:35

import django.utils.timezone
import secrets
import string
from django.db import migrations, models


def generate_join_code():
    """Helper for migration to generate a unique join code."""
    alphabet = string.ascii_uppercase + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(6))


def populate_join_codes(apps, schema_editor):
    Organisation = apps.get_model('organisations', 'Organisation')
    for org in Organisation.objects.all():
        while True:
            code = generate_join_code()
            if not Organisation.objects.filter(join_code=code).exists():
                org.join_code = code
                org.save(update_fields=["join_code"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_reliability_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='join_code_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='join_code_valid_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='join_code_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationmember',
            name='is_exam_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(populate_join_codes, migrations.RunPython.noop),
    ]
