# Generated by Django 5.0.6 on 2026-09-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisation_join_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
